ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS stop_price DECIMAL(18,6),
    ADD COLUMN IF NOT EXISTS time_in_force VARCHAR(10),
    ADD COLUMN IF NOT EXISTS extended_hours BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE orders_archive
    ADD COLUMN IF NOT EXISTS stop_price DECIMAL(18,6),
    ADD COLUMN IF NOT EXISTS time_in_force VARCHAR(10),
    ADD COLUMN IF NOT EXISTS extended_hours BOOLEAN NOT NULL DEFAULT FALSE;
